// Generated by dts-bundle v0.3.0

declare module 'uservoice' {
    export class Client {
        constructor(ClientData: IClientData);
        LoginAsOwner(): void;
        LoginAsUser(email: string): void;
    }
    export interface IClientData {
        SubdomainName: string;
        ApiKey: string;
        ApiSecret?: string;
        CallBack?: string;
        Token?: string;
        Secret?: string;
        UservoiceDomain?: string;
        Protocol?: string;
    }
}

