// Generated by dts-bundle v0.3.0

declare module 'uservoice' {
    export class Client {
        constructor(ClientData: IClientData);
        Get(endpoint: string): Promise<any>;
        Post(endpoint: string, data?: any): Promise<{}>;
        Delete(endpoint: string): Promise<any>;
        Put(endpoint: string, data?: any): Promise<{}>;
    }
    export interface IClientData {
        SubdomainName: string;
        ApiKey: string;
        ApiSecret?: string;
        CallBack?: string;
        Token?: string;
        Secret?: string;
        UservoiceDomain?: string;
        Protocol?: string;
    }
}

